### ISSUE TITLE
安装总是失败。或者黑屏

### ISSUE THREAD

**Issue by henceing** [dark-knifes/azurlinefuckyou#1]
直接下载这里的apk会黑屏。然后用mT管理器加两部分代码之后会安装失败或者打不开。请问能分享一下可以直接使用华为渠道的apk？

**Comment by dark-knifes** [comment]
这里的是古早版本的，有问题

**Comment by dark-knifes** [comment]
在原来apk上修改就行 记得把dev_liu.so复制进lib去

> 直接下载这里的apk会黑屏。然后用mT管理器加两部分代码之后会安装失败或者打不开。请问能分享一下可以直接使用华为渠道的apk？

**Comment by dark-knifes** [comment]
可以看我另一个仓库的教程

**Comment by dark-knifes** [comment]
https://github.com/dark-knifes/azurlane_anti_name
